import type { MenuCategory, MenuItem } from "@/types/content";

// NOTE: placeholder menu — replace with real data via Sanity.
export const menu: MenuCategory[] = [
  {
    id: "paket-botram",
    name: "Paket Botram",
    sundanese: "Botram",
    description: "Paket besar untuk 4 orang, disantap lesehan bareng keluarga.",
    items: [
      {
        id: "paket-botram-bakakak",
        name: "Paket Botram Bakakak",
        description: "Nasi liwet, bakakak goreng/bakar, tahu, tempe, pete goreng, peda merah, cobek kangkung, lalab & sambel untuk 4 orang.",
        price: 170000,
        tags: ["favorit", "rekomendasi"],
        signature: true,
        tone: "ayam",
      },
      {
        id: "paket-botram-gurame",
        name: "Paket Botram Gurame",
        description: "Nasi liwet, gurame goreng/bakar, tahu, tempe, pete goreng, peda merah, cobek kangkung, lalab & sambel untuk 4 orang.",
        price: 170000,
        tags: ["favorit"],
        signature: true,
        tone: "ikan",
      },
    ],
  },
  {
    id: "paket-keluarga",
    name: "Paket Keluarga",
    sundanese: "Sakulawarga",
    description: "Paket hemat untuk 4 orang dengan nasi bakul dan lauk lengkap.",
    items: [
      {
        id: "paket-keluarga-bakakak",
        name: "Paket Keluarga Bakakak",
        description: "Nasi bakul, bakakak goreng/bakar, mendoan, sayur asem, cah kangkung, lalab & sambel untuk 4 orang.",
        price: 150000,
        tags: ["favorit"],
        signature: true,
        tone: "ayam",
      },
      {
        id: "paket-keluarga-gurame",
        name: "Paket Keluarga Gurame",
        description: "Nasi bakul, gurame goreng/bakar, tahu, tempe, sayur asem, cah kangkung, lalab & sambel untuk 4 orang.",
        price: 150000,
        tags: ["favorit"],
        tone: "ikan",
      },
    ],
  },
  {
    id: "ayam-bebek-puyuh",
    name: "Ayam, Bebek & Puyuh Satuan",
    sundanese: "Hayam",
    description: "Aneka ayam, bebek, dan puyuh dibakar atau digoreng dadakan.",
    items: [
      {
        id: "ayam-bakakak-goreng",
        name: "Ayam Bakakak Goreng",
        description: "Ayam kampung utuh digoreng kremes renyah, disajikan dengan sambal dadakan.",
        price: 77000,
        tags: ["rekomendasi"],
        signature: true,
        tone: "ayam",
      },
      {
        id: "ayam-bakakak-bakar",
        name: "Ayam Bakakak Bakar",
        description: "Ayam kampung utuh dibakar bumbu kuning meresap, harum aroma arang.",
        price: 82000,
        tags: ["favorit", "rekomendasi"],
        signature: true,
        tone: "ayam",
      },
      {
        id: "ayam-serundeng",
        name: "Ayam Serundeng",
        description: "Ayam goreng berbalut serundeng kelapa gurih.",
        price: 15000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-cabe-ijo",
        name: "Ayam Cabe Ijo",
        description: "Ayam goreng disiram sambal cabe hijau pedas segar.",
        price: 15000,
        tags: ["pedas"],
        tone: "ayam",
      },
      {
        id: "ayam-penyet",
        name: "Ayam Penyet",
        description: "Ayam goreng dipenyet di atas sambal ulek pedas.",
        price: 16000,
        tags: ["pedas"],
        tone: "ayam",
      },
      {
        id: "ayam-geprek",
        name: "Ayam Geprek",
        description: "Ayam crispy digeprek dengan sambal bawang menggigit.",
        price: 16000,
        tags: ["pedas", "favorit"],
        tone: "ayam",
      },
      {
        id: "ayam-goreng",
        name: "Ayam Goreng",
        description: "Ayam goreng bumbu kuning yang gurih dan empuk.",
        price: 23000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-bakar",
        name: "Ayam Bakar",
        description: "Ayam bakar bumbu kecap manis dengan aroma panggang.",
        price: 23000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-sangrai",
        name: "Ayam Sangrai",
        description: "Ayam disangrai bersama bumbu rempah hingga meresap.",
        price: 23000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-kremes",
        name: "Ayam Kremes",
        description: "Ayam goreng bertabur kremes renyah berlimpah.",
        price: 24000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-kampung-goreng",
        name: "Ayam Kampung Goreng",
        description: "Ayam kampung goreng dengan daging padat dan gurih.",
        price: 35000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-kampung-sangrai",
        name: "Ayam Kampung Sangrai",
        description: "Ayam kampung disangrai bumbu rempah khas.",
        price: 35000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-kampung-bakar",
        name: "Ayam Kampung Bakar",
        description: "Ayam kampung dibakar bumbu kuning meresap sampai ke tulang.",
        price: 35000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "ayam-kampung-kremes",
        name: "Ayam Kampung Kremes",
        description: "Ayam kampung goreng bertabur kremes renyah.",
        price: 36000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "bebek-goreng",
        name: "Bebek Goreng",
        description: "Bebek goreng empuk dengan bumbu meresap, tanpa bau amis.",
        price: 33000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "bebek-bakar",
        name: "Bebek Bakar",
        description: "Bebek bakar bumbu kecap dengan aroma arang.",
        price: 33000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "bebek-sangrai",
        name: "Bebek Sangrai",
        description: "Bebek disangrai rempah hingga gurih meresap.",
        price: 33000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "bebek-kremes",
        name: "Bebek Kremes",
        description: "Bebek goreng bertabur kremes renyah berlimpah.",
        price: 34000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "bebek-serundeng",
        name: "Bebek Serundeng",
        description: "Bebek goreng berbalut serundeng kelapa gurih.",
        price: 33000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "puyuh-goreng",
        name: "Puyuh Goreng",
        description: "Burung puyuh goreng mungil yang gurih dan renyah.",
        price: 28000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "puyuh-bakar",
        name: "Puyuh Bakar",
        description: "Burung puyuh dibakar bumbu kecap manis.",
        price: 29000,
        tags: [],
        tone: "ayam",
      },
    ],
  },
  {
    id: "gurame-nila",
    name: "Gurame & Nila (500gr)",
    sundanese: "Lauk Cai",
    description: "Ikan gurame dan nila segar ukuran 500gr, digoreng atau dibakar.",
    items: [
      {
        id: "gurame-goreng",
        name: "Gurame Goreng",
        description: "Gurame segar digoreng garing sampai renyah di pinggir.",
        price: 80000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "gurame-bakar",
        name: "Gurame Bakar",
        description: "Gurame dibakar bumbu kecap dengan aroma panggang menggoda.",
        price: 85000,
        tags: ["favorit"],
        signature: true,
        tone: "ikan",
      },
      {
        id: "gurame-pesmol",
        name: "Gurame Pesmol",
        description: "Gurame goreng disiram kuah pesmol kuning asam pedas.",
        price: 85000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "gurame-asam-manis",
        name: "Gurame Asam Manis",
        description: "Gurame goreng dengan saus asam manis kaya rasa.",
        price: 85000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "nila-goreng",
        name: "Nila Goreng",
        description: "Ikan nila digoreng garing, gurih sampai ke pinggir.",
        price: 48000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "nila-bakar",
        name: "Nila Bakar",
        description: "Ikan nila dibakar bumbu kecap dengan aroma arang.",
        price: 52000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "nila-pesmol",
        name: "Nila Pesmol",
        description: "Ikan nila goreng disiram kuah pesmol asam pedas.",
        price: 52000,
        tags: [],
        tone: "ikan",
      },
    ],
  },
  {
    id: "sop-iga",
    name: "Sop & Iga",
    sundanese: "Sop",
    description: "Iga sapi empuk dan sop berkuah hangat yang menyegarkan.",
    items: [
      {
        id: "iga-bakar",
        name: "Iga Bakar",
        description: "Iga sapi dibakar bumbu kecap, empuk dan harum.",
        price: 42500,
        tags: ["favorit"],
        tone: "daging",
      },
      {
        id: "iga-penyet",
        name: "Iga Penyet",
        description: "Iga sapi goreng dipenyet di atas sambal pedas.",
        price: 42500,
        tags: ["pedas"],
        tone: "daging",
      },
      {
        id: "iga-barbeque",
        name: "Iga Barbeque",
        description: "Iga sapi dengan saus barbeque manis gurih.",
        price: 42500,
        tags: [],
        tone: "daging",
      },
      {
        id: "sop-iga",
        name: "Sop Iga",
        description: "Iga sapi dalam kuah sop bening hangat dan segar.",
        price: 42500,
        tags: ["favorit"],
        signature: true,
        tone: "daging",
      },
      {
        id: "sop-iga-bakar",
        name: "Sop Iga Bakar",
        description: "Sop iga dengan tambahan iga bakar harum.",
        price: 45000,
        tags: [],
        tone: "daging",
      },
      {
        id: "sop-iga-penyet",
        name: "Sop Iga Penyet",
        description: "Sop iga disajikan dengan iga penyet pedas.",
        price: 45000,
        tags: [],
        tone: "daging",
      },
      {
        id: "sop-ikan-dori",
        name: "Sop Ikan Dori",
        description: "Potongan ikan dori lembut dalam kuah sop bening.",
        price: 35000,
        tags: [],
        tone: "ikan",
      },
    ],
  },
  {
    id: "sate-tongseng",
    name: "Sate & Tongseng",
    sundanese: "Sate",
    description: "Sate dan tongseng bumbu rempah khas, hangat menggugah selera.",
    items: [
      {
        id: "sate-sapi",
        name: "Sate Sapi",
        description: "Sate daging sapi empuk dengan bumbu kacang atau kecap.",
        price: 40000,
        tags: [],
        tone: "daging",
      },
      {
        id: "sate-kambing",
        name: "Sate Kambing",
        description: "Sate kambing muda yang empuk dan harum.",
        price: 45000,
        tags: ["favorit"],
        tone: "daging",
      },
      {
        id: "tongseng-sapi",
        name: "Tongseng Sapi",
        description: "Tongseng daging sapi berkuah santan gurih pedas.",
        price: 32000,
        tags: [],
        tone: "daging",
      },
      {
        id: "tongseng-kambing",
        name: "Tongseng Kambing",
        description: "Tongseng kambing dengan kuah rempah kaya rasa.",
        price: 37500,
        tags: [],
        tone: "daging",
      },
      {
        id: "sate-kulit-ayam",
        name: "Sate Kulit Ayam",
        description: "Sate kulit ayam gurih dan renyah, favorit pendamping.",
        price: 30000,
        tags: [],
        tone: "ayam",
      },
    ],
  },
  {
    id: "sambal-bakar",
    name: "Sambal Bakar",
    sundanese: "Sambel Bakar",
    description: "Hidangan bakar berbalut sambal pedas yang menggugah selera.",
    items: [
      {
        id: "sambal-bakar-ayam-goreng",
        name: "Sambal Bakar Ayam Goreng",
        description: "Ayam goreng dibakar bersama sambal pedas meresap.",
        price: 31000,
        tags: ["pedas", "favorit"],
        signature: true,
        tone: "sambal",
      },
      {
        id: "sambal-bakar-ayam-kampung-goreng",
        name: "Sambal Bakar Ayam Kampung Goreng",
        description: "Ayam kampung goreng berbalut sambal bakar pedas.",
        price: 43000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambal-bakar-bebek-goreng",
        name: "Sambal Bakar Bebek Goreng",
        description: "Bebek goreng dibakar dengan sambal pedas menggigit.",
        price: 41000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambal-bakar-nila-goreng",
        name: "Sambal Bakar Nila Goreng",
        description: "Nila goreng berbalut sambal bakar pedas gurih.",
        price: 48000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambal-bakar-telor-ceplok",
        name: "Sambal Bakar Telor Ceplok",
        description: "Telor ceplok dibakar bersama sambal pedas.",
        price: 14000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambal-bakar-puyuh-goreng",
        name: "Sambal Bakar Puyuh Goreng",
        description: "Puyuh goreng berbalut sambal bakar pedas.",
        price: 36000,
        tags: ["pedas"],
        tone: "sambal",
      },
    ],
  },
  {
    id: "oseng-mercon",
    name: "Oseng Mercon",
    sundanese: "Oseng",
    description: "Oseng super pedas yang meledak di lidah, bukan untuk yang lemah.",
    items: [
      {
        id: "oseng-mercon-sapi",
        name: "Oseng Mercon Sapi",
        description: "Daging sapi dioseng cabai rawit melimpah, pedasnya meledak.",
        price: 40000,
        tags: ["pedas", "favorit"],
        tone: "sambal",
      },
      {
        id: "oseng-mercon-kambing",
        name: "Oseng Mercon Kambing",
        description: "Daging kambing dioseng cabai rawit super pedas.",
        price: 45000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "oseng-mercon-ayam",
        name: "Oseng Mercon Ayam",
        description: "Ayam dioseng cabai rawit melimpah, pedas menggigit.",
        price: 32000,
        tags: ["pedas"],
        tone: "sambal",
      },
    ],
  },
  {
    id: "nasi-ayam-ds",
    name: "Nasi Ayam DS",
    sundanese: "Sangu Hayam",
    description: "Nasi dengan olahan ayam spesial ala Dadakan Sunda.",
    items: [
      {
        id: "nasi-ayam-lada-hitam",
        name: "Nasi Ayam Lada Hitam",
        description: "Nasi dengan ayam tumis saus lada hitam gurih.",
        price: 32000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-ayam-teriyaki",
        name: "Nasi Ayam Teriyaki",
        description: "Nasi dengan ayam saus teriyaki manis gurih.",
        price: 32000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-ayam-karage",
        name: "Nasi Ayam Karage",
        description: "Nasi dengan ayam karage crispy ala Jepang.",
        price: 34000,
        tags: ["favorit"],
        tone: "nasi",
      },
      {
        id: "nasi-ayam-kari",
        name: "Nasi Ayam Kari",
        description: "Nasi dengan ayam berkuah kari rempah yang hangat.",
        price: 32000,
        tags: [],
        tone: "nasi",
      },
    ],
  },
  {
    id: "nasi-goreng",
    name: "Nasi Goreng",
    sundanese: "Sangu Goreng",
    description: "Nasi goreng dadakan dengan beragam pilihan isian.",
    items: [
      {
        id: "nasi-goreng-kampung",
        name: "Nasi Goreng Kampung",
        description: "Nasi goreng kampung sederhana dengan bumbu khas.",
        price: 26000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-goreng-sosis",
        name: "Nasi Goreng Sosis",
        description: "Nasi goreng gurih dengan irisan sosis.",
        price: 27000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-goreng-seafood",
        name: "Nasi Goreng Seafood",
        description: "Nasi goreng dengan campuran seafood segar.",
        price: 28000,
        tags: ["favorit"],
        tone: "nasi",
      },
      {
        id: "nasi-goreng-kambing",
        name: "Nasi Goreng Kambing",
        description: "Nasi goreng dengan daging kambing dan rempah.",
        price: 30000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-goreng-ds",
        name: "Nasi Goreng DS",
        description: "Nasi goreng spesial ala Dadakan Sunda dengan isian lengkap.",
        price: 30000,
        tags: ["rekomendasi"],
        signature: true,
        tone: "nasi",
      },
    ],
  },
  {
    id: "mie-kwetiaw",
    name: "Mie & Kwetiaw",
    sundanese: "Mihun",
    description: "Olahan mie dan kwetiau goreng maupun kuah.",
    items: [
      {
        id: "mie-tektek-goreng-kuah",
        name: "Mie Tektek Goreng / Kuah",
        description: "Mie tektek goreng atau kuah dengan bumbu khas pinggir jalan.",
        price: 26000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "mie-goreng-cabe-ijo",
        name: "Mie Goreng Cabe Ijo",
        description: "Mie goreng dengan sambal cabe hijau pedas segar.",
        price: 26000,
        tags: ["pedas"],
        tone: "nasi",
      },
      {
        id: "mie-goreng-geprek",
        name: "Mie Goreng Geprek",
        description: "Mie goreng disajikan dengan ayam geprek pedas.",
        price: 29000,
        tags: ["pedas", "favorit"],
        tone: "nasi",
      },
      {
        id: "kwetiaw-goreng-ayam",
        name: "Kwetiaw Goreng Ayam",
        description: "Kwetiau goreng dengan suwiran ayam gurih.",
        price: 26000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "kwetiaw-goreng-seafood",
        name: "Kwetiaw Goreng Seafood",
        description: "Kwetiau goreng dengan campuran seafood segar.",
        price: 27000,
        tags: [],
        tone: "nasi",
      },
    ],
  },
  {
    id: "special-ff",
    name: "Special FF",
    sundanese: "Istimewa",
    description: "Menu western istimewa, dari steak hingga fish & chip.",
    items: [
      {
        id: "chicken-katsu",
        name: "Chicken Katsu",
        description: "Ayam katsu crispy disajikan dengan saus spesial.",
        price: 35000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "chicken-steak",
        name: "Chicken Steak",
        description: "Steak ayam dengan saus gurih dan kentang.",
        price: 35000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "grill-sosis-barbeque",
        name: "Grill Sosis Barbeque",
        description: "Sosis bakar dengan saus barbeque manis gurih.",
        price: 30000,
        tags: [],
        tone: "daging",
      },
      {
        id: "fish-dan-chip",
        name: "Fish & Chip",
        description: "Ikan goreng tepung crispy dengan kentang goreng.",
        price: 37000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "sirloin-steak",
        name: "Sirloin Steak",
        description: "Steak sirloin sapi juicy dengan saus pilihan.",
        price: 47500,
        tags: ["rekomendasi"],
        signature: true,
        tone: "daging",
      },
    ],
  },
  {
    id: "paket-ayam-boiler",
    name: "Paket Ayam Boiler",
    sundanese: "Sapaket Hayam",
    description: "Paket nasi dengan ayam boiler dan pelengkap.",
    items: [
      {
        id: "paket-ayam-serundeng",
        name: "Paket Ayam Serundeng",
        description: "Nasi, ayam serundeng, lalab & sambel.",
        price: 22000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-ayam-cabe-ijo",
        name: "Paket Ayam Cabe Ijo",
        description: "Nasi, ayam cabe ijo pedas, lalab & sambel.",
        price: 22000,
        tags: ["pedas"],
        tone: "ayam",
      },
      {
        id: "paket-ayam-penyet",
        name: "Paket Ayam Penyet",
        description: "Nasi, ayam penyet, lalab & sambel.",
        price: 23000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-ayam-geprek",
        name: "Paket Ayam Geprek",
        description: "Nasi, ayam geprek pedas, lalab & sambel.",
        price: 23000,
        tags: ["pedas"],
        tone: "ayam",
      },
    ],
  },
  {
    id: "paket-ayam-pejantan",
    name: "Paket Ayam Pejantan",
    sundanese: "Sapaket Jago",
    description: "Paket nasi dengan ayam pejantan berdaging padat.",
    items: [
      {
        id: "paket-ayam-goreng",
        name: "Paket Ayam Goreng",
        description: "Nasi, ayam pejantan goreng, lalab & sambel.",
        price: 30000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-ayam-bakar",
        name: "Paket Ayam Bakar",
        description: "Nasi, ayam pejantan bakar, lalab & sambel.",
        price: 30000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-ayam-sangrai",
        name: "Paket Ayam Sangrai",
        description: "Nasi, ayam pejantan sangrai, lalab & sambel.",
        price: 30000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-ayam-kremes",
        name: "Paket Ayam Kremes",
        description: "Nasi, ayam pejantan kremes, lalab & sambel.",
        price: 31000,
        tags: [],
        tone: "ayam",
      },
    ],
  },
  {
    id: "paket-bebek",
    name: "Paket Bebek",
    sundanese: "Sapaket Meri",
    description: "Paket nasi dengan bebek pilihan dan pelengkap.",
    items: [
      {
        id: "paket-bebek-goreng",
        name: "Paket Bebek Goreng",
        description: "Nasi, bebek goreng, lalab & sambel.",
        price: 39000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-bebek-sangrai",
        name: "Paket Bebek Sangrai",
        description: "Nasi, bebek sangrai, lalab & sambel.",
        price: 39000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-bebek-bakar",
        name: "Paket Bebek Bakar",
        description: "Nasi, bebek bakar, lalab & sambel.",
        price: 39000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-bebek-kremes",
        name: "Paket Bebek Kremes",
        description: "Nasi, bebek kremes, lalab & sambel.",
        price: 40000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-bebek-serundeng",
        name: "Paket Bebek Serundeng",
        description: "Nasi, bebek serundeng, lalab & sambel.",
        price: 39000,
        tags: [],
        tone: "ayam",
      },
    ],
  },
  {
    id: "paket-entog",
    name: "Paket Entog",
    sundanese: "Sapaket Entog",
    description: "Paket nasi dengan entog gurih dan pelengkap.",
    items: [
      {
        id: "paket-entog-goreng",
        name: "Paket Entog Goreng",
        description: "Nasi, entog goreng, lalab & sambel.",
        price: 40000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-entog-sangrai",
        name: "Paket Entog Sangrai",
        description: "Nasi, entog sangrai, lalab & sambel.",
        price: 40000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-entog-bakar",
        name: "Paket Entog Bakar",
        description: "Nasi, entog bakar, lalab & sambel.",
        price: 40000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-entog-kremes",
        name: "Paket Entog Kremes",
        description: "Nasi, entog kremes, lalab & sambel.",
        price: 41000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-entog-serundeng",
        name: "Paket Entog Serundeng",
        description: "Nasi, entog serundeng, lalab & sambel.",
        price: 40000,
        tags: [],
        tone: "ayam",
      },
    ],
  },
  {
    id: "paket-ayam-kampung",
    name: "Paket Ayam Kampung",
    sundanese: "Sapaket Kampung",
    description: "Paket nasi dengan ayam kampung berdaging padat.",
    items: [
      {
        id: "paket-kampung-goreng",
        name: "Paket Kampung Goreng",
        description: "Nasi, ayam kampung goreng, lalab & sambel.",
        price: 41000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-kampung-sangrai",
        name: "Paket Kampung Sangrai",
        description: "Nasi, ayam kampung sangrai, lalab & sambel.",
        price: 41000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-kampung-bakar",
        name: "Paket Kampung Bakar",
        description: "Nasi, ayam kampung bakar, lalab & sambel.",
        price: 41000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-kampung-kremes",
        name: "Paket Kampung Kremes",
        description: "Nasi, ayam kampung kremes, lalab & sambel.",
        price: 42000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "paket-kampung-serundeng",
        name: "Paket Kampung Serundeng",
        description: "Nasi, ayam kampung serundeng, lalab & sambel.",
        price: 41000,
        tags: [],
        tone: "ayam",
      },
    ],
  },
  {
    id: "paket-nasi-liwet",
    name: "Paket Nasi Liwet DS",
    sundanese: "Sangu Liwet",
    description: "Nasi liwet pulen dengan lauk pilihan ala Dadakan Sunda.",
    items: [
      {
        id: "paket-liwet-ayam-serundeng",
        name: "Paket Liwet Ayam Serundeng",
        description: "Nasi liwet dengan ayam serundeng dan pelengkap.",
        price: 25000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-ayam-goreng-bakar",
        name: "Paket Liwet Ayam Goreng / Bakar",
        description: "Nasi liwet dengan ayam goreng atau bakar.",
        price: 31000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-ayam-kremes",
        name: "Paket Liwet Ayam Kremes",
        description: "Nasi liwet dengan ayam kremes renyah.",
        price: 32000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-ayam-kampung-goreng-bakar",
        name: "Paket Liwet Ayam Kampung Goreng / Bakar",
        description: "Nasi liwet dengan ayam kampung goreng atau bakar.",
        price: 43000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-ayam-kampung-kremes",
        name: "Paket Liwet Ayam Kampung Kremes",
        description: "Nasi liwet dengan ayam kampung kremes.",
        price: 44000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-bebek-goreng-bakar",
        name: "Paket Liwet Bebek Goreng / Bakar",
        description: "Nasi liwet dengan bebek goreng atau bakar.",
        price: 42000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-bebek-kremes",
        name: "Paket Liwet Bebek Kremes",
        description: "Nasi liwet dengan bebek kremes renyah.",
        price: 43000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-entog-goreng-bakar",
        name: "Paket Liwet Entog Goreng / Bakar",
        description: "Nasi liwet dengan entog goreng atau bakar.",
        price: 43000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "paket-liwet-entog-kremes",
        name: "Paket Liwet Entog Kremes",
        description: "Nasi liwet dengan entog kremes renyah.",
        price: 44000,
        tags: [],
        tone: "nasi",
      },
    ],
  },
  {
    id: "paket-tutug-oncom",
    name: "Paket Nasi Tutug Oncom",
    sundanese: "Sangu TO",
    description: "Nasi tutug oncom khas Sunda dengan lauk pilihan.",
    items: [
      {
        id: "nasi-to-ayam-serundeng",
        name: "Nasi TO Ayam Serundeng",
        description: "Nasi tutug oncom dengan ayam serundeng.",
        price: 27000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-ayam-goreng-bakar",
        name: "Nasi TO Ayam Goreng / Bakar",
        description: "Nasi tutug oncom dengan ayam goreng atau bakar.",
        price: 33000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-ayam-kremes",
        name: "Nasi TO Ayam Kremes",
        description: "Nasi tutug oncom dengan ayam kremes renyah.",
        price: 34000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-ayam-kampung-goreng-bakar",
        name: "Nasi TO Ayam Kampung Goreng / Bakar",
        description: "Nasi tutug oncom dengan ayam kampung goreng atau bakar.",
        price: 45000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-ayam-kampung-kremes",
        name: "Nasi TO Ayam Kampung Kremes",
        description: "Nasi tutug oncom dengan ayam kampung kremes.",
        price: 46000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-bebek-goreng-bakar",
        name: "Nasi TO Bebek Goreng / Bakar",
        description: "Nasi tutug oncom dengan bebek goreng atau bakar.",
        price: 44000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-bebek-kremes",
        name: "Nasi TO Bebek Kremes",
        description: "Nasi tutug oncom dengan bebek kremes renyah.",
        price: 45000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-entog-goreng-bakar",
        name: "Nasi TO Entog Goreng / Bakar",
        description: "Nasi tutug oncom dengan entog goreng atau bakar.",
        price: 45000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-to-entog-kremes",
        name: "Nasi TO Entog Kremes",
        description: "Nasi tutug oncom dengan entog kremes renyah.",
        price: 46000,
        tags: [],
        tone: "nasi",
      },
    ],
  },
  {
    id: "porsian",
    name: "Porsian",
    sundanese: "Saporsi",
    description: "Lauk dan pelengkap per porsi siap santap.",
    items: [
      {
        id: "nasi-putih",
        name: "Nasi Putih",
        description: "Nasi putih panas mengepul.",
        price: 6000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-liwet",
        name: "Nasi Liwet",
        description: "Nasi liwet pulen gurih wangi daun salam.",
        price: 9000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "nasi-tutug-oncom",
        name: "Nasi Tutug Oncom",
        description: "Nasi tutug oncom khas Sunda yang gurih.",
        price: 10000,
        tags: [],
        tone: "nasi",
      },
      {
        id: "tahu-4-pcs",
        name: "Tahu (4 Pcs)",
        description: "Tahu goreng renyah isi empat potong.",
        price: 7000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "tempe-4-pcs",
        name: "Tempe (4 Pcs)",
        description: "Tempe goreng gurih isi empat potong.",
        price: 7000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "mendoan-4-pcs",
        name: "Mendoan (4 Pcs)",
        description: "Tempe mendoan tipis berbalut tepung, isi empat.",
        price: 12000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "telor-ceplok",
        name: "Telor Ceplok",
        description: "Telur ceplok mata sapi.",
        price: 6000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "telor-dadar",
        name: "Telor Dadar",
        description: "Telur dadar tebal gurih khas Sunda.",
        price: 11000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "kol-goreng",
        name: "Kol Goreng",
        description: "Kol goreng renyah pendamping lalaban.",
        price: 7000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "lalab",
        name: "Lalab",
        description: "Aneka lalaban segar pendamping sambal.",
        price: 5000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "sayur-asem",
        name: "Sayur Asem",
        description: "Sayur asem segar dengan kuah asam menyegarkan.",
        price: 10000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "pepes-ayam",
        name: "Pepes Ayam",
        description: "Pepes ayam berbumbu, dikukus dalam daun pisang.",
        price: 20000,
        tags: [],
        tone: "ayam",
      },
      {
        id: "pepes-ikan",
        name: "Pepes Ikan",
        description: "Pepes ikan berbumbu, dikukus harum dalam daun.",
        price: 20000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "gepuk",
        name: "Gepuk",
        description: "Empal daging sapi manis gurih yang empuk.",
        price: 20000,
        tags: [],
        tone: "daging",
      },
      {
        id: "fuyunghai",
        name: "Fuyunghai",
        description: "Telur dadar isi sayur disiram saus asam manis.",
        price: 20000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "babat",
        name: "Babat",
        description: "Babat sapi empuk berbumbu meresap.",
        price: 20000,
        tags: [],
        tone: "daging",
      },
      {
        id: "tamusu",
        name: "Tamusu",
        description: "Tamusu khas dengan bumbu meresap.",
        price: 22000,
        tags: [],
        tone: "daging",
      },
      {
        id: "salada-goreng",
        name: "Salada Goreng",
        description: "Selada air goreng renyah berbumbu.",
        price: 13000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "perkedel-kentang-4-pcs",
        name: "Perkedel Kentang (4 Pcs)",
        description: "Perkedel kentang gurih isi empat potong.",
        price: 14000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "perkedel-jagung-4-pcs",
        name: "Perkedel Jagung (4 Pcs)",
        description: "Perkedel jagung manis gurih isi empat potong.",
        price: 14000,
        tags: [],
        tone: "sundaan",
      },
    ],
  },
  {
    id: "cemilan",
    name: "Cemilan",
    sundanese: "Cacamilan",
    description: "Gorengan dan cemilan hangat untuk teman ngobrol.",
    items: [
      {
        id: "kentang-goreng",
        name: "Kentang Goreng",
        description: "Kentang goreng renyah, gurih di luar lembut di dalam.",
        price: 13000,
        tags: [],
        tone: "cemilan",
      },
      {
        id: "singkong-goreng",
        name: "Singkong Goreng",
        description: "Singkong goreng renyah berbumbu.",
        price: 14000,
        tags: [],
        tone: "cemilan",
      },
      {
        id: "jamur-crispy",
        name: "Jamur Crispy",
        description: "Jamur tepung crispy gurih dan renyah.",
        price: 17500,
        tags: [],
        tone: "cemilan",
      },
      {
        id: "jamur-geprek",
        name: "Jamur Geprek",
        description: "Jamur crispy digeprek dengan sambal pedas.",
        price: 20000,
        tags: ["pedas"],
        tone: "cemilan",
      },
      {
        id: "calamari-cumi-tepung",
        name: "Calamari / Cumi Tepung",
        description: "Cumi tepung crispy gurih dengan saus.",
        price: 27500,
        tags: [],
        tone: "ikan",
      },
      {
        id: "pancake-ice-cream",
        name: "Pancake Ice Cream",
        description: "Pancake lembut disajikan dengan es krim.",
        price: 17500,
        tags: [],
        tone: "cemilan",
      },
      {
        id: "ice-cream-sundae-goreng",
        name: "Ice Cream Sundae / Goreng",
        description: "Es krim sundae atau es krim goreng yang manis.",
        price: 15000,
        tags: [],
        tone: "cemilan",
      },
    ],
  },
  {
    id: "sundaan",
    name: "Sundaan",
    sundanese: "Sundaeun",
    description: "Lauk khas Sunda penggugah selera, segar dan menggoda.",
    items: [
      {
        id: "karedok-karedok-lenca",
        name: "Karedok / Karedok Lenca",
        description: "Sayuran mentah segar dengan bumbu kacang khas Sunda.",
        price: 15000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "lotek",
        name: "Lotek",
        description: "Sayuran rebus disiram bumbu kacang gurih.",
        price: 15000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "pencok-kacang",
        name: "Pencok Kacang",
        description: "Pencok kacang panjang dengan bumbu khas.",
        price: 15000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "peda-merah",
        name: "Peda Merah",
        description: "Ikan peda merah asin gurih, teman nasi panas.",
        price: 10000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "jambal-roti",
        name: "Jambal Roti",
        description: "Ikan jambal roti asin gurih yang khas.",
        price: 10000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "asin-sepat",
        name: "Asin Sepat",
        description: "Ikan asin sepat renyah, pendamping sambal.",
        price: 8000,
        tags: [],
        tone: "ikan",
      },
      {
        id: "jengkol-goreng",
        name: "Jengkol Goreng",
        description: "Jengkol goreng empuk berbumbu untuk pencinta jengkol.",
        price: 10000,
        tags: [],
        tone: "sundaan",
      },
      {
        id: "pete-goreng",
        name: "Pete Goreng",
        description: "Pete goreng gurih, aroma khas menggoda.",
        price: 15000,
        tags: [],
        tone: "sundaan",
      },
    ],
  },
  {
    id: "cah-cahan",
    name: "Cah-Cahan",
    sundanese: "Cacahan",
    description: "Tumis sayuran segar yang renyah dan gurih.",
    items: [
      {
        id: "cah-kangkung",
        name: "Cah Kangkung",
        description: "Kangkung tumis bawang putih yang renyah.",
        price: 14000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "cah-kangkung-hot-plate",
        name: "Cah Kangkung Hot Plate",
        description: "Cah kangkung disajikan panas di atas hot plate.",
        price: 22000,
        tags: ["favorit"],
        tone: "sayur",
      },
      {
        id: "cah-kangkung-cobek",
        name: "Cah Kangkung Cobek",
        description: "Cah kangkung dengan sambal cobek pedas.",
        price: 19000,
        tags: ["pedas"],
        tone: "sayur",
      },
      {
        id: "cah-toge",
        name: "Cah Toge",
        description: "Tumis toge segar yang renyah.",
        price: 14000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "cah-jamur",
        name: "Cah Jamur",
        description: "Tumis jamur gurih dengan bumbu bawang.",
        price: 16000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "cah-brokoli",
        name: "Cah Brokoli",
        description: "Tumis brokoli segar yang renyah dan sehat.",
        price: 17000,
        tags: [],
        tone: "sayur",
      },
      {
        id: "cah-genjer",
        name: "Cah Genjer",
        description: "Tumis genjer khas dengan bumbu gurih.",
        price: 15000,
        tags: [],
        tone: "sayur",
      },
    ],
  },
  {
    id: "sambel",
    name: "Sambel",
    sundanese: "Sambel",
    description: "Aneka sambal dadakan, diulek langsung saat dipesan.",
    items: [
      {
        id: "sambel-dadak",
        name: "Sambel Dadak",
        description: "Sambal mentah dadakan segar dan pedas.",
        price: 8000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambel-goang",
        name: "Sambel Goang",
        description: "Sambal goang cabai rawit dan bawang yang super pedas.",
        price: 8000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambel-terasi",
        name: "Sambel Terasi",
        description: "Sambal terasi gurih pedas khas Sunda.",
        price: 7000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambel-hejo",
        name: "Sambel Hejo",
        description: "Sambal hijau cabai rawit yang segar pedas.",
        price: 7000,
        tags: ["pedas"],
        tone: "sambal",
      },
      {
        id: "sambel-korek",
        name: "Sambel Korek",
        description: "Sambal korek bawang yang pedas menggigit.",
        price: 7000,
        tags: ["pedas"],
        tone: "sambal",
      },
    ],
  },
  {
    id: "varian-jus",
    name: "Varian Jus",
    sundanese: "Cai Bubuah",
    description: "Jus buah segar diperas dadakan tanpa pengawet.",
    items: [
      {
        id: "jus-wortel",
        name: "Jus Wortel",
        description: "Jus wortel segar kaya vitamin.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-tomat",
        name: "Jus Tomat",
        description: "Jus tomat segar yang menyehatkan.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-jeruk",
        name: "Jus Jeruk",
        description: "Jus jeruk peras segar dan menyegarkan.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-melon",
        name: "Jus Melon",
        description: "Jus melon manis dan menyegarkan.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-jambu",
        name: "Jus Jambu",
        description: "Jus jambu biji merah segar.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-mangga",
        name: "Jus Mangga",
        description: "Jus mangga manis dan kental.",
        price: 16000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "jus-buah-naga",
        name: "Jus Buah Naga",
        description: "Jus buah naga merah segar dan sehat.",
        price: 16000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-sirsak",
        name: "Jus Sirsak",
        description: "Jus sirsak segar dengan rasa asam manis.",
        price: 16000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-alpukat",
        name: "Jus Alpukat",
        description: "Jus alpukat creamy dengan cokelat.",
        price: 16000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "jus-strawberry",
        name: "Jus Strawberry",
        description: "Jus strawberry segar manis asam.",
        price: 16000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jus-nanas",
        name: "Jus Nanas",
        description: "Jus nanas segar yang menyegarkan.",
        price: 16000,
        tags: [],
        tone: "minuman",
      },
    ],
  },
  {
    id: "milkshake",
    name: "Milkshake",
    sundanese: "Susuan",
    description: "Milkshake creamy aneka rasa.",
    items: [
      {
        id: "vanilla-shake",
        name: "Vanilla Shake",
        description: "Milkshake vanilla lembut dan creamy.",
        price: 19000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "strawberry-shake",
        name: "Strawberry Shake",
        description: "Milkshake strawberry manis dan segar.",
        price: 19000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "coklat-shake",
        name: "Coklat Shake",
        description: "Milkshake cokelat kental dan creamy.",
        price: 19000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "chocochip-shake",
        name: "Chocochip Shake",
        description: "Milkshake cokelat dengan taburan chocochip.",
        price: 19000,
        tags: [],
        tone: "minuman",
      },
    ],
  },
  {
    id: "teh",
    name: "Teh",
    sundanese: "Entehan",
    description: "Aneka teh panas dan dingin.",
    items: [
      {
        id: "teh-manis-panas-dingin",
        name: "Teh Manis Panas / Dingin",
        description: "Teh manis disajikan panas atau dingin.",
        price: 5000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "lemon-tea-panas-dingin",
        name: "Lemon Tea Panas / Dingin",
        description: "Teh lemon segar panas atau dingin.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "teh-tarik-panas-dingin",
        name: "Teh Tarik Panas / Dingin",
        description: "Teh tarik creamy panas atau dingin.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "teh-tawar-dingin",
        name: "Teh Tawar Dingin",
        description: "Teh tawar dingin yang menyegarkan.",
        price: 3000,
        tags: [],
        tone: "minuman",
      },
    ],
  },
  {
    id: "float",
    name: "Float",
    sundanese: "Ngambang",
    description: "Minuman soda float dengan es krim mengambang.",
    items: [
      {
        id: "cappuccino-float",
        name: "Cappuccino Float",
        description: "Cappuccino dingin dengan es krim mengambang.",
        price: 17500,
        tags: [],
        tone: "minuman",
      },
      {
        id: "choco-float",
        name: "Choco Float",
        description: "Cokelat dingin dengan es krim mengambang.",
        price: 17500,
        tags: [],
        tone: "minuman",
      },
      {
        id: "coca-cola-float",
        name: "Coca Cola Float",
        description: "Coca cola dengan es krim mengambang.",
        price: 17500,
        tags: [],
        tone: "minuman",
      },
      {
        id: "sodaberry-float",
        name: "Sodaberry Float",
        description: "Soda berry segar dengan es krim mengambang.",
        price: 17500,
        tags: [],
        tone: "minuman",
      },
    ],
  },
  {
    id: "kopi",
    name: "Kopi",
    sundanese: "Kopi",
    description: "Racikan kopi panas dan dingin.",
    items: [
      {
        id: "kopi-lampung",
        name: "Kopi Lampung",
        description: "Kopi hitam robusta Lampung yang kuat.",
        price: 7000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "kopi-hitam",
        name: "Kopi Hitam",
        description: "Kopi hitam tubruk yang pekat.",
        price: 8000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "kopi-susu",
        name: "Kopi Susu",
        description: "Kopi susu hangat yang gurih manis.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "es-kopi-susu",
        name: "Es Kopi Susu",
        description: "Kopi susu dingin yang segar.",
        price: 12000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "cappuccino",
        name: "Cappuccino",
        description: "Cappuccino hangat dengan busa lembut.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "es-cappuccino",
        name: "Es Cappuccino",
        description: "Cappuccino dingin yang creamy.",
        price: 12000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "es-kopi",
        name: "Es Kopi",
        description: "Kopi hitam dingin yang menyegarkan.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "kopi-susu-aren",
        name: "Kopi Susu Aren",
        description: "Kopi susu dengan gula aren khas.",
        price: 11000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "es-kopi-susu-aren",
        name: "Es Kopi Susu Aren",
        description: "Es kopi susu gula aren yang segar manis.",
        price: 13000,
        tags: ["favorit"],
        signature: true,
        tone: "minuman",
      },
    ],
  },
  {
    id: "boba",
    name: "Boba",
    sundanese: "Boba",
    description: "Minuman boba kenyal aneka rasa.",
    items: [
      {
        id: "taro",
        name: "Taro",
        description: "Minuman taro ungu creamy dengan boba kenyal.",
        price: 17000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "tiramisu",
        name: "Tiramisu",
        description: "Minuman tiramisu manis dengan boba kenyal.",
        price: 17000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "red-velvet",
        name: "Red Velvet",
        description: "Minuman red velvet creamy dengan boba.",
        price: 17000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "green-tea",
        name: "Green Tea",
        description: "Green tea latte dingin dengan boba kenyal.",
        price: 19000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "hot-green-tea",
        name: "Hot Green Tea",
        description: "Green tea latte hangat dengan boba.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "thai-tea",
        name: "Thai Tea",
        description: "Thai tea creamy dingin dengan boba kenyal.",
        price: 19000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "hot-thai-tea",
        name: "Hot Thai Tea",
        description: "Thai tea creamy hangat dengan boba.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
    ],
  },
  {
    id: "varian-lainnya",
    name: "Varian Lainnya",
    sundanese: "Sajabana",
    description: "Aneka minuman segar dan hangat lainnya.",
    items: [
      {
        id: "es-jeruk",
        name: "Es Jeruk",
        description: "Es jeruk peras segar yang menyegarkan.",
        price: 13000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "jeruk-panas",
        name: "Jeruk Panas",
        description: "Jeruk peras hangat yang menyegarkan.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "happy-fanta",
        name: "Happy Fanta",
        description: "Minuman soda fanta spesial yang segar.",
        price: 14000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "italian-soda",
        name: "Italian Soda",
        description: "Italian soda warna-warni yang segar.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "lemon-squash",
        name: "Lemon Squash",
        description: "Soda lemon segar yang menyegarkan.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "mojito",
        name: "Mojito",
        description: "Mojito mint segar tanpa alkohol.",
        price: 15000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "mojito-strawberry",
        name: "Mojito Strawberry",
        description: "Mojito strawberry mint yang segar.",
        price: 17000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "mojito-lemonade",
        name: "Mojito Lemonade",
        description: "Mojito lemonade mint yang menyegarkan.",
        price: 17000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "manggo-yakult",
        name: "Manggo Yakult",
        description: "Mangga dan yakult yang segar manis asam.",
        price: 15000,
        tags: ["favorit"],
        tone: "minuman",
      },
      {
        id: "milo-panas",
        name: "Milo Panas",
        description: "Milo cokelat hangat yang nikmat.",
        price: 8000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "milo-dingin",
        name: "Milo Dingin",
        description: "Milo cokelat dingin yang segar.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "susu-soda",
        name: "Susu Soda",
        description: "Susu soda manis yang menyegarkan.",
        price: 13000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "bandrek",
        name: "Bandrek",
        description: "Bandrek jahe hangat khas Sunda.",
        price: 8000,
        tags: [],
        tone: "minuman",
      },
      {
        id: "bandrek-susu",
        name: "Bandrek Susu",
        description: "Bandrek jahe hangat dengan susu.",
        price: 10000,
        tags: [],
        tone: "minuman",
      },
    ],
  },
];

export const allItems: MenuItem[] = menu.flatMap((c) => c.items);

export const signatureItems: MenuItem[] = allItems.filter((i) => i.signature);
